{
 "title": "Market Monitor",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "bucket_interval",
    "query": "1m,5m,15m,30m,1h,4h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "symbol",
    "query": "SELECT DISTINCT symbol FROM binance_kline_spot ORDER BY symbol ASC"
   }
  ]
 },
 "panels": [
  {
   "title": "Spot and Perpetual Future Market Activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Binance $bucket_interval $symbol (spot)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$bucket_interval', open_time) AS time,\n  symbol,\n  first(open, open_time) AS \"open\",\n  MAX(high) AS \"high\",\n  MIN(low) AS \"low\",\n  last(close, open_time) AS \"close\"\nFROM binance_kline_spot \n  WHERE symbol = '$symbol' \n    AND open_time > $__timeFrom()::timestamptz and open_time < $__timeTo()::timestamptz\nGROUP BY symbol, time_bucket('$bucket_interval', open_time);  "
    }
   ]
  },
  {
   "title": "Binance $bucket_interval $symbol (future)",
   "type": "candlestick",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$bucket_interval', open_time) AS time,\n  symbol,\n  first(open, open_time) AS \"open\",\n  MAX(high) AS \"high\",\n  MIN(low) AS \"low\",\n  last(close, open_time) AS \"close\"\nFROM binance_kline_future \n  WHERE symbol = '$symbol' \n    AND open_time > $__timeFrom()::timestamptz and open_time < $__timeTo()::timestamptz\nGROUP BY symbol, time_bucket('$bucket_interval', open_time);  "
    }
   ]
  },
  {
   "title": "Binance $bucket_interval $symbol (spot volume, USDT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$bucket_interval', open_time) AS time,\n  symbol,\n  SUM(quote_asset_volume) AS volume\nFROM binance_kline_spot \n  WHERE symbol = '$symbol' \n    AND open_time > $__timeFrom()::timestamptz and open_time < $__timeTo()::timestamptz\nGROUP BY symbol, time_bucket('$bucket_interval', open_time);  "
    }
   ]
  },
  {
   "title": "Binance $bucket_interval $symbol (future volume, USDT)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  time_bucket('$bucket_interval', open_time) AS time,\n  symbol,\n  SUM(quote_asset_volume) AS volume\nFROM binance_kline_future \n  WHERE symbol = '$symbol' \n    AND open_time > $__timeFrom()::timestamptz and open_time < $__timeTo()::timestamptz\nGROUP BY symbol, time_bucket('$bucket_interval', open_time);  "
    }
   ]
  },
  { "title": "Funding Rate Perpetual Future", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Binance $symbol funding rate (in %)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n  time,\n  funding_rate * 100 as funding_rate\nFROM binance_funding_future \n  WHERE symbol = '$symbol' \n    AND time > $__timeFrom()::timestamptz and time < $__timeTo()::timestamptz"
    }
   ]
  }
 ]
}